apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 4200 # Puerto en el que el servicio escucha
      targetPort: 4200  # Puerto del contenedor
      nodePort: 30420