apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app  # Nombre del deployment
  namespace: default
spec:
  replicas: 2  # Número inicial de réplicas
  selector:
    matchLabels:
      app: backend-app  # Nombre del deployment
  template:
    metadata:
      labels:
        app: backend-app  # Nombre del deployment
    spec:
      containers:
      - name: backend-app  # Nombre del deployment
        image: backend:latest  # Nombre de la imagen creada
        imagePullPolicy: Never  # No se necesita descargar la imagen
        ports:
        - containerPort: 8080  # Puerto que expone tu aplicación
        resources:
          requests:
            cpu: 250m 
            memory: 512Mi 
          limits:
            cpu: 500m 
            memory: 512Mi 