apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 8080     # Puerto en el que el servicio escucha
      targetPort: 8080  # Puerto del contenedor