apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: k8s-demo-app
  ports:
    - protocol: TCP
      port: 31000     # Puerto en el que el servicio escucha
      targetPort: 8080  # Puerto del contenedor
      nodePort: 32000  # Puerto en el que el servicio escucha en el nodo